# Generated by Django 5.2.7 on 2025-12-19 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_goal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goal',
            new_name='Shot',
        ),
    ]
